# Example from Class 18-Feb
Working through the various derivatives of the Lagrange Equation example from class.

In [1]:
using SymPy

In [2]:
# First time you need to run this:
# using Pkg
# Pkg.add("SymPy")
# using SymPy

In [3]:
L, m, g, t, Jg = symbols("L, m, g, t, J_G", positive=true)
τ,f = symbols("tau, f")
θ = SymFunction("theta")(t)
;

In [4]:
ihat= [1,0,0]
jhat = [0,1,0]
khat = [0,0,1]
r = L*(sin(θ)*ihat - cos(θ)*jhat)

3-element Array{Sym,1}:
  L*sin(theta(t))
 -L*cos(theta(t))
                0

In [5]:
# this fails because it can't work on an array
diff(r,t)

MethodError: MethodError: no method matching diff(::Array{Sym,1}, ::Sym)
Closest candidates are:
  diff(::AbstractArray{T,1} where T) at multidimensional.jl:736
  diff(::AbstractArray{T,N}; dims) where {T, N} at multidimensional.jl:769
  diff(!Matched::SymPy.SymbolicObject, ::Any...; kwargs...) at C:\Users\tim\.julia\packages\SymPy\xIl2Y\src\importexport.jl:70

So let's talk about list comprehensions

In [6]:
out = zeros(4)
for i = 1:4
    out[i] = i
end
out

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [7]:
[ i+j for i in 1:4, j in 1:2 ]

4×2 Array{Int64,2}:
 2  3
 3  4
 4  5
 5  6

In [8]:
v = [ diff(R,t) for R in r ]

3-element Array{Sym,1}:
 L*cos(theta(t))*Derivative(theta(t), t)
 L*sin(theta(t))*Derivative(theta(t), t)
                                       0

Now we can build the kinetic energy $T$

In [9]:
T = 1//2*m*sum( v .* v )  + 1//2*Jg*diff(θ,t)^2 |> simplify

                           2
/       2  \ /d           \ 
\J_G + L *m/*|--(theta(t))| 
             \dt          / 
----------------------------
             2              

As well as the potential energy

In [10]:
V = m*g*r[2]

-L*g*m*cos(theta(t))

Once we build the Lagrangian $L$ then we're pretty much done

In [11]:
Lag = T - V

                                                 2
                      /       2  \ /d           \ 
                      \J_G + L *m/*|--(theta(t))| 
                                   \dt          / 
L*g*m*cos(theta(t)) + ----------------------------
                                   2              

In [12]:
diff(Lag, diff(θ,t), t) - diff(Lag, θ) - (f*L*cos(θ) + τ)

                                                                2          
                                                 /       2  \  d           
-L*f*cos(theta(t)) + L*g*m*sin(theta(t)) - tau + \J_G + L *m/*---(theta(t))
                                                                2          
                                                              dt           

We could make the Lagrange Equation a function too.  That way if we have many generalized coordinates we don't have to write it out each time.

In [13]:
LagEq(L,q) = diff(L, diff(q,t),t) - diff(L, q)

LagEq (generic function with 1 method)

In [14]:
LagEq(Lag,θ)

                                     2          
                      /       2  \  d           
L*g*m*sin(theta(t)) + \J_G + L *m/*---(theta(t))
                                     2          
                                   dt           